In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
concatenated_data_rfc = pd.read_excel("concatenated_table_1116_logistic.xlsx",index_col=0) 
#same data as used in logistic model will be used here

In [3]:
concatenated_data_rfc.head()

,12/09/22,12/08/22,12/07/22,12/06/22,12/05/22,12/04/22,12/03/22,12/02/22,12/01/22,11/30/22,...,12/17/12,12/14/12,12/13/12,12/12/12,12/11/12,12/10/12,12/07/12,12/06/12,12/05/12,12/04/12
Date,,,,,,,,,,,,,,,,,,,,,
my,1.0,0.0,0.0,0.0,2.0,0.0,23.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
life,1.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tried,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
music,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bring,1.0,0.0,0.0,0.0,2.0,0.0,2.0,1.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
concatenated_data_rfc

,12/09/22,12/08/22,12/07/22,12/06/22,12/05/22,12/04/22,12/03/22,12/02/22,12/01/22,11/30/22,...,12/17/12,12/14/12,12/13/12,12/12/12,12/11/12,12/10/12,12/07/12,12/06/12,12/05/12,12/04/12
Date,,,,,,,,,,,,,,,,,,,,,
my,1.0,0.0,0.0,0.0,2.0,0.0,23.0,0.000000,0.000000,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
life,1.0,0.0,0.0,0.0,1.0,0.0,2.0,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tried,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
music,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.000000,1.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bring,1.0,0.0,0.0,0.0,2.0,0.0,2.0,1.000000,2.000000,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ledge,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Glassnode,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SFIX,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Change_stock_prices,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.606007,-1.207631,6.725867,...,1.777778,0.0,-4.680851,0.0,1.731602,0.0,-0.436681,0.444444,0.0,-0.440529
Change_binary,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
concatenated_data_rfc.dropna(axis=1,inplace=True)
concatenated_data_rfc

,12/02/22,12/01/22,11/30/22,11/29/22,11/28/22,11/25/22,11/23/22,11/22/22,11/21/22,11/18/22,...,06/10/21,06/09/21,06/08/21,06/07/21,06/04/21,06/03/21,06/02/21,06/01/21,05/28/21,05/27/21
Date,,,,,,,,,,,,,,,,,,,,,
my,0.000000,0.000000,1.000000,0.00000,1.00000,0.000000,1.000000,0.000000,0.000000,2.000000,...,93.000000,11.000000,1.00000,11.000000,11.000000,16.000000,18.000000,14.000000,3.000000,5.000000
life,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,1.000000,0.000000,0.000000,...,8.000000,0.000000,0.00000,2.000000,1.000000,1.000000,4.000000,0.000000,0.000000,0.000000
tried,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,2.000000,...,2.000000,0.000000,0.00000,0.000000,2.000000,0.000000,1.000000,0.000000,0.000000,1.000000
music,1.000000,1.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
bring,1.000000,2.000000,1.000000,1.00000,0.00000,0.000000,1.000000,0.000000,0.000000,2.000000,...,2.000000,0.000000,0.00000,0.000000,6.000000,4.000000,1.000000,0.000000,1.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ledge,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
Glassnode,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
SFIX,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
Change_stock_prices,1.606007,-1.207631,6.725867,-2.24877,1.64481,-1.188804,5.548194,0.759058,-4.537958,-2.626317,...,1.033335,-0.562973,-3.11552,2.245539,3.332643,-4.810568,-2.418848,-0.621207,-0.520286,1.707376
Change_binary,1.000000,0.000000,1.000000,0.00000,1.00000,0.000000,1.000000,1.000000,0.000000,0.000000,...,1.000000,0.000000,0.00000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000

In [7]:
concatenated_data_rfc.drop(['Change_stock_prices'],axis=0,inplace =True)

In [8]:
concatenated_data_rfc

,12/02/22,12/01/22,11/30/22,11/29/22,11/28/22,11/25/22,11/23/22,11/22/22,11/21/22,11/18/22,...,06/10/21,06/09/21,06/08/21,06/07/21,06/04/21,06/03/21,06/02/21,06/01/21,05/28/21,05/27/21
Date,,,,,,,,,,,,,,,,,,,,,
my,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,2.0,...,93.0,11.0,1.0,11.0,11.0,16.0,18.0,14.0,3.0,5.0
life,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,8.0,0.0,0.0,2.0,1.0,1.0,4.0,0.0,0.0,0.0
tried,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,2.0,0.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,1.0
music,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
bring,1.0,2.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,2.0,...,2.0,0.0,0.0,0.0,6.0,4.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
counterproductive,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
ledge,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Glassnode,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
SFIX,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
Change_binary,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0

In [9]:
# Removing words that don't appear for atleast 50 days or are smaller than two characters
minimum_occurance = 50 #minimum number of days a word should appear
minimum_word_length = 3
rare_short_words = []
for idx in concatenated_data_rfc.index[:-1]:
    if ((concatenated_data_rfc.loc[idx] == 0).sum()<minimum_occurance) or (len(idx)<minimum_word_length):
        rare_short_words.append(idx)

In [15]:
TSLA_data_rfc = []
TSLA_data_rfc = concatenated_data_rfc.drop(rare_short_words)

In [17]:
TSLA_data_rfc = TSLA_data_rfc.transpose()
TSLA_data_rfc

Date,life,tried,music,bring,Yet,saddens,divide,decided,longer,allow,...,Untrusting,clamp,whipping,Logic,unison,counterproductive,ledge,Glassnode,SFIX,Change_binary
12/02/22,0.0,0.0,1.0,1.0,4.0,0.0,0.0,1.0,1.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
12/01/22,0.0,0.0,1.0,2.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11/30/22,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
11/29/22,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11/28/22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
06/03/21,1.0,0.0,0.0,4.0,1.0,0.0,0.0,1.0,8.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
06/02/21,4.0,1.0,0.0,1.0,3.0,0.0,0.0,1.0,7.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
06/01/21,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05/28/21,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05/27/21,0.0,1.0,0.0,0.0,2.0,0.0,0.0,2.0,3.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,3.0,1.0

## Random Forest Classifier

In [51]:
X = TSLA_data_rfc[TSLA_data_rfc.columns[:-1]]

In [52]:
y = TSLA_data_rfc['Change_binary']

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [55]:
from sklearn.ensemble import RandomForestClassifier

In [68]:
rfc = RandomForestClassifier(n_estimators=500)

In [69]:
rfc.fit(X_train,y_train)

RandomForestClassifier(n_estimators=500)

## Prediction

In [70]:
predictions = rfc.predict(X_test)

In [71]:
from sklearn.metrics import classification_report,confusion_matrix

In [72]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         0.0       0.44      0.57      0.50        54
         1.0       0.49      0.35      0.41        62

    accuracy                           0.46       116
   macro avg       0.46      0.46      0.45       116
weighted avg       0.46      0.46      0.45       116

In [73]:
print(confusion_matrix(y_test,predictions))

[[31 23]
 [40 22]]