### K means is unsupervised learning method. We are using this just to check if our data has any clusters to start with. In reality, we will never use unsupervised method as we do. have labels.

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [11]:
concatenated_data = pd.read_excel("concatenated_table_1116_logistic.xlsx",index_col=0) 
#same data as used in logistic model will be used here

In [12]:
concatenated_data.head()

,12/09/22,12/08/22,12/07/22,12/06/22,12/05/22,12/04/22,12/03/22,12/02/22,12/01/22,11/30/22,...,12/17/12,12/14/12,12/13/12,12/12/12,12/11/12,12/10/12,12/07/12,12/06/12,12/05/12,12/04/12
Date,,,,,,,,,,,,,,,,,,,,,
my,1.0,0.0,0.0,0.0,2.0,0.0,23.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
life,1.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tried,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
music,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bring,1.0,0.0,0.0,0.0,2.0,0.0,2.0,1.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
concatenated_data

,12/09/22,12/08/22,12/07/22,12/06/22,12/05/22,12/04/22,12/03/22,12/02/22,12/01/22,11/30/22,...,12/17/12,12/14/12,12/13/12,12/12/12,12/11/12,12/10/12,12/07/12,12/06/12,12/05/12,12/04/12
Date,,,,,,,,,,,,,,,,,,,,,
my,1.0,0.0,0.0,0.0,2.0,0.0,23.0,0.000000,0.000000,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
life,1.0,0.0,0.0,0.0,1.0,0.0,2.0,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tried,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
music,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.000000,1.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bring,1.0,0.0,0.0,0.0,2.0,0.0,2.0,1.000000,2.000000,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ledge,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Glassnode,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SFIX,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Change_stock_prices,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.606007,-1.207631,6.725867,...,1.777778,0.0,-4.680851,0.0,1.731602,0.0,-0.436681,0.444444,0.0,-0.440529
Change_binary,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
concatenated_data.dropna(axis=1,inplace=True)
concatenated_data

,12/02/22,12/01/22,11/30/22,11/29/22,11/28/22,11/25/22,11/23/22,11/22/22,11/21/22,11/18/22,...,06/10/21,06/09/21,06/08/21,06/07/21,06/04/21,06/03/21,06/02/21,06/01/21,05/28/21,05/27/21
Date,,,,,,,,,,,,,,,,,,,,,
my,0.000000,0.000000,1.000000,0.00000,1.00000,0.000000,1.000000,0.000000,0.000000,2.000000,...,93.000000,11.000000,1.00000,11.000000,11.000000,16.000000,18.000000,14.000000,3.000000,5.000000
life,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,1.000000,0.000000,0.000000,...,8.000000,0.000000,0.00000,2.000000,1.000000,1.000000,4.000000,0.000000,0.000000,0.000000
tried,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,2.000000,...,2.000000,0.000000,0.00000,0.000000,2.000000,0.000000,1.000000,0.000000,0.000000,1.000000
music,1.000000,1.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
bring,1.000000,2.000000,1.000000,1.00000,0.00000,0.000000,1.000000,0.000000,0.000000,2.000000,...,2.000000,0.000000,0.00000,0.000000,6.000000,4.000000,1.000000,0.000000,1.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ledge,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
Glassnode,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
SFIX,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
Change_stock_prices,1.606007,-1.207631,6.725867,-2.24877,1.64481,-1.188804,5.548194,0.759058,-4.537958,-2.626317,...,1.033335,-0.562973,-3.11552,2.245539,3.332643,-4.810568,-2.418848,-0.621207,-0.520286,1.707376
Change_binary,1.000000,0.000000,1.000000,0.00000,1.00000,0.000000,1.000000,1.000000,0.000000,0.000000,...,1.000000,0.000000,0.00000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000

In [15]:
#removing conrrect labels "Change_binary" to use concatenated_data_kmc in KMeans which is unsupervised learning. 
concatenated_data_kmc = concatenated_data.drop(['Change_stock_prices','Change_binary'],axis=0)

In [16]:
concatenated_data_kmc

,12/02/22,12/01/22,11/30/22,11/29/22,11/28/22,11/25/22,11/23/22,11/22/22,11/21/22,11/18/22,...,06/10/21,06/09/21,06/08/21,06/07/21,06/04/21,06/03/21,06/02/21,06/01/21,05/28/21,05/27/21
Date,,,,,,,,,,,,,,,,,,,,,
my,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,2.0,...,93.0,11.0,1.0,11.0,11.0,16.0,18.0,14.0,3.0,5.0
life,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,8.0,0.0,0.0,2.0,1.0,1.0,4.0,0.0,0.0,0.0
tried,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,2.0,0.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,1.0
music,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
bring,1.0,2.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,2.0,...,2.0,0.0,0.0,0.0,6.0,4.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
unison,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
counterproductive,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
ledge,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Glassnode,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
SFIX,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0

In [20]:
# Removing words that don't appear for atleast 50 days or are smaller than two characters
minimum_occurance = 50 #minimum number of days a word should appear
minimum_word_length = 3
rare_short_words = []
for idx in concatenated_data_kmc.index:
    if ((concatenated_data_kmc.loc[idx] == 0).sum()<minimum_occurance) or (len(idx)<minimum_word_length):
        rare_short_words.append(idx)

In [21]:
TSLA_data_kmc = []
TSLA_data_kmc = concatenated_data_kmc.drop(rare_short_words)

In [22]:
TSLA_data_kmc = TSLA_data_kmc.transpose()
TSLA_data_kmc

Date,life,tried,music,bring,Yet,saddens,divide,decided,longer,allow,...,definitively,Untrusting,clamp,whipping,Logic,unison,counterproductive,ledge,Glassnode,SFIX
12/02/22,0.0,0.0,1.0,1.0,4.0,0.0,0.0,1.0,1.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12/01/22,0.0,0.0,1.0,2.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11/30/22,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11/29/22,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11/28/22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
06/03/21,1.0,0.0,0.0,4.0,1.0,0.0,0.0,1.0,8.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
06/02/21,4.0,1.0,0.0,1.0,3.0,0.0,0.0,1.0,7.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
06/01/21,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05/28/21,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05/27/21,0.0,1.0,0.0,0.0,2.0,0.0,0.0,2.0,3.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,3.0

## K Means Cluster Creation

In [23]:
from sklearn.cluster import KMeans

In [24]:
kmeans = KMeans(n_clusters=2)

In [27]:
kmeans.fit(TSLA_data_kmc)

KMeans(n_clusters=2)

In [30]:
kmeans.cluster_centers_

array([[1.26785714e+00, 6.96428571e-01, 2.50000000e-01, ...,
        1.73472348e-18, 3.46944695e-18, 0.00000000e+00],
       [3.45588235e-01, 2.90441176e-01, 7.72058824e-02, ...,
        3.67647059e-03, 7.35294118e-03, 1.10294118e-02]])

In [34]:
kmeans.labels_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1], dtype=int32)

## Evaluation
### We compare these labels with the change_binary column in concatenated_data table

In [40]:
concatenated_data = concatenated_data.transpose()

from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(concatenated_data['Change_binary'],kmeans.labels_))
print(classification_report(concatenated_data['Change_binary'],kmeans.labels_))

[[ 62 131]
 [ 50 141]]
              precision    recall  f1-score   support

         0.0       0.55      0.32      0.41       193
         1.0       0.52      0.74      0.61       191

    accuracy                           0.53       384
   macro avg       0.54      0.53      0.51       384
weighted avg       0.54      0.53      0.51       384